/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables;


import com.canaan.privilege.db.DubboTest;
import com.canaan.privilege.db.Keys;
import com.canaan.privilege.db.tables.records.SysButtonRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysButton extends TableImpl<SysButtonRecord> {

    private static final long serialVersionUID = 1407672777;

    /**
     * The reference instance of <code>dubbo_test.sys_button</code>
     */
    public static final SysButton SYS_BUTTON = new SysButton();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysButtonRecord> getRecordType() {
        return SysButtonRecord.class;
    }

    /**
     * The column <code>dubbo_test.sys_button.id</code>. 按钮ID
     */
    public final TableField<SysButtonRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "按钮ID");

    /**
     * The column <code>dubbo_test.sys_button.button_code</code>. 按钮编码
     */
    public final TableField<SysButtonRecord, String> BUTTON_CODE = createField("button_code", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "按钮编码");

    /**
     * The column <code>dubbo_test.sys_button.button_name</code>. 按钮名称
     */
    public final TableField<SysButtonRecord, String> BUTTON_NAME = createField("button_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "按钮名称");

    /**
     * The column <code>dubbo_test.sys_button.button_url</code>. 按钮URL
     */
    public final TableField<SysButtonRecord, String> BUTTON_URL = createField("button_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "按钮URL");

    /**
     * The column <code>dubbo_test.sys_button.menu_id</code>. 菜单ID
     */
    public final TableField<SysButtonRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER, this, "菜单ID");

    /**
     * Create a <code>dubbo_test.sys_button</code> table reference
     */
    public SysButton() {
        this("sys_button", null);
    }

    /**
     * Create an aliased <code>dubbo_test.sys_button</code> table reference
     */
    public SysButton(String alias) {
        this(alias, SYS_BUTTON);
    }

    private SysButton(String alias, Table<SysButtonRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysButton(String alias, Table<SysButtonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DubboTest.DUBBO_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SysButtonRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SYS_BUTTON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysButtonRecord> getPrimaryKey() {
        return Keys.KEY_SYS_BUTTON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysButtonRecord>> getKeys() {
        return Arrays.<UniqueKey<SysButtonRecord>>asList(Keys.KEY_SYS_BUTTON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysButton as(String alias) {
        return new SysButton(alias, this);
    }

    /**
     * Rename this table
     */
    public SysButton rename(String name) {
        return new SysButton(name, null);
    }
}
