/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables;


import com.canaan.privilege.db.DubboTest;
import com.canaan.privilege.db.Keys;
import com.canaan.privilege.db.tables.records.SysElementRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysElement extends TableImpl<SysElementRecord> {

    private static final long serialVersionUID = -1242875395;

    /**
     * The reference instance of <code>dubbo_test.sys_element</code>
     */
    public static final SysElement SYS_ELEMENT = new SysElement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysElementRecord> getRecordType() {
        return SysElementRecord.class;
    }

    /**
     * The column <code>dubbo_test.sys_element.id</code>.
     */
    public final TableField<SysElementRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dubbo_test.sys_element.code</code>.
     */
    public final TableField<SysElementRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

    /**
     * The column <code>dubbo_test.sys_element.name</code>.
     */
    public final TableField<SysElementRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>dubbo_test.sys_element.url</code>.
     */
    public final TableField<SysElementRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>dubbo_test.sys_element.element_type</code>.
     */
    public final TableField<SysElementRecord, String> ELEMENT_TYPE = createField("element_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>dubbo_test.sys_element.menu_id</code>.
     */
    public final TableField<SysElementRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>dubbo_test.sys_element</code> table reference
     */
    public SysElement() {
        this("sys_element", null);
    }

    /**
     * Create an aliased <code>dubbo_test.sys_element</code> table reference
     */
    public SysElement(String alias) {
        this(alias, SYS_ELEMENT);
    }

    private SysElement(String alias, Table<SysElementRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysElement(String alias, Table<SysElementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DubboTest.DUBBO_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysElementRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ELEMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysElementRecord>> getKeys() {
        return Arrays.<UniqueKey<SysElementRecord>>asList(Keys.KEY_SYS_ELEMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElement as(String alias) {
        return new SysElement(alias, this);
    }

    /**
     * Rename this table
     */
    public SysElement rename(String name) {
        return new SysElement(name, null);
    }
}
