/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables;


import com.canaan.privilege.db.DubboTest;
import com.canaan.privilege.db.Keys;
import com.canaan.privilege.db.tables.records.SysMenuRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu extends TableImpl<SysMenuRecord> {

    private static final long serialVersionUID = -430052181;

    /**
     * The reference instance of <code>dubbo_test.sys_menu</code>
     */
    public static final SysMenu SYS_MENU = new SysMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysMenuRecord> getRecordType() {
        return SysMenuRecord.class;
    }

    /**
     * The column <code>dubbo_test.sys_menu.id</code>.
     */
    public final TableField<SysMenuRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dubbo_test.sys_menu.menu_code</code>.
     */
    public final TableField<SysMenuRecord, String> MENU_CODE = createField("menu_code", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>dubbo_test.sys_menu.menu_name</code>.
     */
    public final TableField<SysMenuRecord, String> MENU_NAME = createField("menu_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>dubbo_test.sys_menu.menu_url</code>.
     */
    public final TableField<SysMenuRecord, String> MENU_URL = createField("menu_url", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>dubbo_test.sys_menu.parent_id</code>.
     */
    public final TableField<SysMenuRecord, Integer> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("-1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>dubbo_test.sys_menu</code> table reference
     */
    public SysMenu() {
        this("sys_menu", null);
    }

    /**
     * Create an aliased <code>dubbo_test.sys_menu</code> table reference
     */
    public SysMenu(String alias) {
        this(alias, SYS_MENU);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DubboTest.DUBBO_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SysMenuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SYS_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysMenuRecord> getPrimaryKey() {
        return Keys.KEY_SYS_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysMenuRecord>>asList(Keys.KEY_SYS_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenu as(String alias) {
        return new SysMenu(alias, this);
    }

    /**
     * Rename this table
     */
    public SysMenu rename(String name) {
        return new SysMenu(name, null);
    }
}
