/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables;


import com.canaan.privilege.db.DubboTest;
import com.canaan.privilege.db.Keys;
import com.canaan.privilege.db.tables.records.SysPrivilegeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPrivilege extends TableImpl<SysPrivilegeRecord> {

    private static final long serialVersionUID = 763372816;

    /**
     * The reference instance of <code>dubbo_test.sys_privilege</code>
     */
    public static final SysPrivilege SYS_PRIVILEGE = new SysPrivilege();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysPrivilegeRecord> getRecordType() {
        return SysPrivilegeRecord.class;
    }

    /**
     * The column <code>dubbo_test.sys_privilege.id</code>.
     */
    public final TableField<SysPrivilegeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dubbo_test.sys_privilege.privilege_code</code>.
     */
    public final TableField<SysPrivilegeRecord, String> PRIVILEGE_CODE = createField("privilege_code", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>dubbo_test.sys_privilege.privilege_name</code>.
     */
    public final TableField<SysPrivilegeRecord, String> PRIVILEGE_NAME = createField("privilege_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>dubbo_test.sys_privilege.source_type</code>.
     */
    public final TableField<SysPrivilegeRecord, String> SOURCE_TYPE = createField("source_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>dubbo_test.sys_privilege.source_id</code>.
     */
    public final TableField<SysPrivilegeRecord, Integer> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>dubbo_test.sys_privilege</code> table reference
     */
    public SysPrivilege() {
        this("sys_privilege", null);
    }

    /**
     * Create an aliased <code>dubbo_test.sys_privilege</code> table reference
     */
    public SysPrivilege(String alias) {
        this(alias, SYS_PRIVILEGE);
    }

    private SysPrivilege(String alias, Table<SysPrivilegeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysPrivilege(String alias, Table<SysPrivilegeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DubboTest.DUBBO_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysPrivilegeRecord> getPrimaryKey() {
        return Keys.KEY_SYS_PRIVILEGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysPrivilegeRecord>> getKeys() {
        return Arrays.<UniqueKey<SysPrivilegeRecord>>asList(Keys.KEY_SYS_PRIVILEGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPrivilege as(String alias) {
        return new SysPrivilege(alias, this);
    }

    /**
     * Rename this table
     */
    public SysPrivilege rename(String name) {
        return new SysPrivilege(name, null);
    }
}
