/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables.records;


import com.canaan.privilege.db.tables.SysElement;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysElementRecord extends UpdatableRecordImpl<SysElementRecord> implements Record6<Integer, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1385592996;

    /**
     * Setter for <code>dubbo_test.sys_element.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dubbo_test.sys_element.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dubbo_test.sys_element.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dubbo_test.sys_element.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dubbo_test.sys_element.element_type</code>.
     */
    public void setElementType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.element_type</code>.
     */
    public String getElementType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dubbo_test.sys_element.menu_id</code>.
     */
    public void setMenuId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_element.menu_id</code>.
     */
    public Integer getMenuId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysElement.SYS_ELEMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysElement.SYS_ELEMENT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysElement.SYS_ELEMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysElement.SYS_ELEMENT.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysElement.SYS_ELEMENT.ELEMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SysElement.SYS_ELEMENT.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getElementType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value5(String value) {
        setElementType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord value6(Integer value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysElementRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysElementRecord
     */
    public SysElementRecord() {
        super(SysElement.SYS_ELEMENT);
    }

    /**
     * Create a detached, initialised SysElementRecord
     */
    public SysElementRecord(Integer id, String code, String name, String url, String elementType, Integer menuId) {
        super(SysElement.SYS_ELEMENT);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, url);
        set(4, elementType);
        set(5, menuId);
    }
}
