/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables.records;


import com.canaan.privilege.db.tables.SysMenu;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends UpdatableRecordImpl<SysMenuRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -708713355;

    /**
     * Setter for <code>dubbo_test.sys_menu.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_menu.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dubbo_test.sys_menu.menu_code</code>.
     */
    public void setMenuCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_menu.menu_code</code>.
     */
    @Size(max = 20)
    public String getMenuCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dubbo_test.sys_menu.menu_name</code>.
     */
    public void setMenuName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_menu.menu_name</code>.
     */
    @Size(max = 50)
    public String getMenuName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dubbo_test.sys_menu.menu_url</code>.
     */
    public void setMenuUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_menu.menu_url</code>.
     */
    @Size(max = 50)
    public String getMenuUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dubbo_test.sys_menu.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_menu.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysMenu.SYS_MENU.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysMenu.SYS_MENU.MENU_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysMenu.SYS_MENU.MENU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysMenu.SYS_MENU.MENU_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SysMenu.SYS_MENU.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMenuCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMenuUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value2(String value) {
        setMenuCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value3(String value) {
        setMenuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value4(String value) {
        setMenuUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value5(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(Integer id, String menuCode, String menuName, String menuUrl, Integer parentId) {
        super(SysMenu.SYS_MENU);

        set(0, id);
        set(1, menuCode);
        set(2, menuName);
        set(3, menuUrl);
        set(4, parentId);
    }
}
