/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables.records;


import com.canaan.privilege.db.tables.SysRolePrivilege;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRolePrivilegeRecord extends UpdatableRecordImpl<SysRolePrivilegeRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 477947351;

    /**
     * Setter for <code>dubbo_test.sys_role_privilege.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_role_privilege.role_id</code>.
     */
    @NotNull
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dubbo_test.sys_role_privilege.privilege_id</code>.
     */
    public void setPrivilegeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_role_privilege.privilege_id</code>.
     */
    @NotNull
    public Integer getPrivilegeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysRolePrivilege.SYS_ROLE_PRIVILEGE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SysRolePrivilege.SYS_ROLE_PRIVILEGE.PRIVILEGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrivilegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRolePrivilegeRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRolePrivilegeRecord value2(Integer value) {
        setPrivilegeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRolePrivilegeRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRolePrivilegeRecord
     */
    public SysRolePrivilegeRecord() {
        super(SysRolePrivilege.SYS_ROLE_PRIVILEGE);
    }

    /**
     * Create a detached, initialised SysRolePrivilegeRecord
     */
    public SysRolePrivilegeRecord(Integer roleId, Integer privilegeId) {
        super(SysRolePrivilege.SYS_ROLE_PRIVILEGE);

        set(0, roleId);
        set(1, privilegeId);
    }
}
