/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables;


import com.canaan.privilege.db.DubboTest;
import com.canaan.privilege.db.Keys;
import com.canaan.privilege.db.tables.records.SysRoleMenuRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenu extends TableImpl<SysRoleMenuRecord> {

    private static final long serialVersionUID = -1010243818;

    /**
     * The reference instance of <code>dubbo_test.sys_role_menu</code>
     */
    public static final SysRoleMenu SYS_ROLE_MENU = new SysRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysRoleMenuRecord> getRecordType() {
        return SysRoleMenuRecord.class;
    }

    /**
     * The column <code>dubbo_test.sys_role_menu.role_id</code>. 角色ID
     */
    public final TableField<SysRoleMenuRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "角色ID");

    /**
     * The column <code>dubbo_test.sys_role_menu.menu_id</code>. 菜单ID
     */
    public final TableField<SysRoleMenuRecord, Integer> MENU_ID = createField("menu_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "菜单ID");

    /**
     * Create a <code>dubbo_test.sys_role_menu</code> table reference
     */
    public SysRoleMenu() {
        this("sys_role_menu", null);
    }

    /**
     * Create an aliased <code>dubbo_test.sys_role_menu</code> table reference
     */
    public SysRoleMenu(String alias) {
        this(alias, SYS_ROLE_MENU);
    }

    private SysRoleMenu(String alias, Table<SysRoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysRoleMenu(String alias, Table<SysRoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DubboTest.DUBBO_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ROLE_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysRoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysRoleMenuRecord>>asList(Keys.KEY_SYS_ROLE_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleMenu as(String alias) {
        return new SysRoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    public SysRoleMenu rename(String name) {
        return new SysRoleMenu(name, null);
    }
}
