/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db;


import com.canaan.privilege.db.tables.SysButton;
import com.canaan.privilege.db.tables.SysMenu;
import com.canaan.privilege.db.tables.SysRole;
import com.canaan.privilege.db.tables.SysRoleButton;
import com.canaan.privilege.db.tables.SysRoleMenu;
import com.canaan.privilege.db.tables.SysUser;
import com.canaan.privilege.db.tables.SysUserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dubbo_test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dubbo_test.sys_button</code>.
     */
    public static final SysButton SYS_BUTTON = com.canaan.privilege.db.tables.SysButton.SYS_BUTTON;

    /**
     * The table <code>dubbo_test.sys_menu</code>.
     */
    public static final SysMenu SYS_MENU = com.canaan.privilege.db.tables.SysMenu.SYS_MENU;

    /**
     * The table <code>dubbo_test.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = com.canaan.privilege.db.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>dubbo_test.sys_role_button</code>.
     */
    public static final SysRoleButton SYS_ROLE_BUTTON = com.canaan.privilege.db.tables.SysRoleButton.SYS_ROLE_BUTTON;

    /**
     * The table <code>dubbo_test.sys_role_menu</code>.
     */
    public static final SysRoleMenu SYS_ROLE_MENU = com.canaan.privilege.db.tables.SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>dubbo_test.sys_user</code>.
     */
    public static final SysUser SYS_USER = com.canaan.privilege.db.tables.SysUser.SYS_USER;

    /**
     * The table <code>dubbo_test.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = com.canaan.privilege.db.tables.SysUserRole.SYS_USER_ROLE;
}
