/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db;


import com.canaan.privilege.db.tables.SysElement;
import com.canaan.privilege.db.tables.SysMenu;
import com.canaan.privilege.db.tables.SysPrivilege;
import com.canaan.privilege.db.tables.SysRole;
import com.canaan.privilege.db.tables.SysRolePrivilege;
import com.canaan.privilege.db.tables.SysUser;
import com.canaan.privilege.db.tables.SysUserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dubbo_test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dubbo_test.sys_element</code>.
     */
    public static final SysElement SYS_ELEMENT = com.canaan.privilege.db.tables.SysElement.SYS_ELEMENT;

    /**
     * The table <code>dubbo_test.sys_menu</code>.
     */
    public static final SysMenu SYS_MENU = com.canaan.privilege.db.tables.SysMenu.SYS_MENU;

    /**
     * The table <code>dubbo_test.sys_privilege</code>.
     */
    public static final SysPrivilege SYS_PRIVILEGE = com.canaan.privilege.db.tables.SysPrivilege.SYS_PRIVILEGE;

    /**
     * The table <code>dubbo_test.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = com.canaan.privilege.db.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>dubbo_test.sys_role_privilege</code>.
     */
    public static final SysRolePrivilege SYS_ROLE_PRIVILEGE = com.canaan.privilege.db.tables.SysRolePrivilege.SYS_ROLE_PRIVILEGE;

    /**
     * The table <code>dubbo_test.sys_user</code>.
     */
    public static final SysUser SYS_USER = com.canaan.privilege.db.tables.SysUser.SYS_USER;

    /**
     * The table <code>dubbo_test.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = com.canaan.privilege.db.tables.SysUserRole.SYS_USER_ROLE;
}
