/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables.records;


import com.canaan.privilege.db.tables.SysRoleButton;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleButtonRecord extends UpdatableRecordImpl<SysRoleButtonRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 609204272;

    /**
     * Setter for <code>dubbo_test.sys_role_button.role_id</code>. 角色ID
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_role_button.role_id</code>. 角色ID
     */
    @NotNull
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dubbo_test.sys_role_button.button_id</code>. 按钮ID
     */
    public void setButtonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_role_button.button_id</code>. 按钮ID
     */
    @NotNull
    public Integer getButtonId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysRoleButton.SYS_ROLE_BUTTON.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SysRoleButton.SYS_ROLE_BUTTON.BUTTON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getButtonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleButtonRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleButtonRecord value2(Integer value) {
        setButtonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleButtonRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleButtonRecord
     */
    public SysRoleButtonRecord() {
        super(SysRoleButton.SYS_ROLE_BUTTON);
    }

    /**
     * Create a detached, initialised SysRoleButtonRecord
     */
    public SysRoleButtonRecord(Integer roleId, Integer buttonId) {
        super(SysRoleButton.SYS_ROLE_BUTTON);

        set(0, roleId);
        set(1, buttonId);
    }
}
