/**
 * This class is generated by jOOQ
 */
package com.canaan.privilege.db.tables.records;


import com.canaan.privilege.db.tables.SysUser;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 117593987;

    /**
     * Setter for <code>dubbo_test.sys_user.id</code>. 用户ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_user.id</code>. 用户ID
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dubbo_test.sys_user.user_name</code>. 用户名
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_user.user_name</code>. 用户名
     */
    @Size(max = 20)
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dubbo_test.sys_user.user_passwd</code>. 密码
     */
    public void setUserPasswd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_user.user_passwd</code>. 密码
     */
    @Size(max = 20)
    public String getUserPasswd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dubbo_test.sys_user.user_mobile</code>. 手机
     */
    public void setUserMobile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_user.user_mobile</code>. 手机
     */
    @Size(max = 12)
    public String getUserMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dubbo_test.sys_user.user_real_name</code>. 真实姓名
     */
    public void setUserRealName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dubbo_test.sys_user.user_real_name</code>. 真实姓名
     */
    @Size(max = 16)
    public String getUserRealName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SysUser.SYS_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysUser.SYS_USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysUser.SYS_USER.USER_PASSWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysUser.SYS_USER.USER_MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.USER_REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPasswd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value3(String value) {
        setUserPasswd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value4(String value) {
        setUserMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value5(String value) {
        setUserRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(Integer id, String userName, String userPasswd, String userMobile, String userRealName) {
        super(SysUser.SYS_USER);

        set(0, id);
        set(1, userName);
        set(2, userPasswd);
        set(3, userMobile);
        set(4, userRealName);
    }
}
