package com.canaan.jgsf.exception;

import lombok.Getter;

public enum ClientExceptionEnum {
	NO_PRIVILEGE_EXCEPTION(403),
	REQUEST_NOT_FOUND(404),
	UN_CHECKED_EXCEPTION(1000),
	NO_BUNDLE_CODE(1001),
	OBJECT_IS_NULL(1002),
	ILLEGAL_ARGUMENT(1003),
	DATA_IS_NOT_VALID(1004),
	DISTRIBUTE_EXCEPTION(1005),
	DISABLE_ACCOUNT_EXCEPTION(1006),
	LOCKED_ACCOUNT_EXCEPTION(1007),
	INCORRECT_CREDENTIALS_EXCEPTION(1008),
	EXCESSIVE_ATTEMPTS_EXCEPTION(1009),
	USER_IS_NOT_LOGIN(1010),
	PAGE_SIZE_IS_TOO_LARGE_EXCEPTION(1011),
	INVALID_PAGE_PARAMS(1012),
	BATCH_SIZE_TOO_LARGE(1013),
	USER_NAME_OR_PASSWD_INVLID(1014),
	ACCOUNT_IS_LOCK(1015),
	TOO_MANY_TIME_FOR_LOGON(1016);
	@Getter
	private  int code;
	

	
	ClientExceptionEnum(final int code){
		this.code = code;
	}
}
